import Card from "./card"

const First_year = () => {
    return (
        <div>
            <Card
            title="Epytodo"
            description="The 'epytodo' project involves building a Todo List application focusing on backend development using Nodejs. It includes setting up a MySQL database, creating a web server with Express, defining environment variables, structuring the project, and securing routes with JWT."
            imageUrl1="/epytodo1.png"
            imageUrl2="/epytodo3.png"
            imageUrl3="/epytodo2.png"
            linkUrl="https://github.com/jeremyarmijo/Epytodo"
            language="Typescript ( Framework Nodejs )"
            type="Web"
            group_size="Trio"
            duration_project="4 Weeks"
            begin_date="30 March"
            /> <br/> <br/>
            <Card
            title="Need4stek"
            description="The 'Need4Stek' project at Epitech involves developing an autonomous driving simulation program. The program create an auto-pilot to control a virtual car navigating through a track based on sensor input data. Key features include interpreting sensor data, implementing steering and speed control algorithms, and optimizing the car's path to avoid obstacles and stay on track."
            imageUrl1="/ia1.png"
            imageUrl2="/ia2.png"
            imageUrl3="/ia3.png"
            linkUrl="https://github.com/jeremyarmijo/Need4stek"
            language="C"
            type="IA"
            group_size="Trio"
            duration_project="4 Weeks"
            begin_date="30 March"
        /> <br/> <br/>
        <Card
            title="Amazed"
            description="The 'amazed' project involves programming robots to navigate complex mazes by finding the shortest path from the entrance to the exit. Required skills include reading standard input, graph analysis, and graph theory. The program must display the robot movements to guide them to the exit while avoiding traffic jams. PS: the python window is a graphic bonus representation of mazes"
            imageUrl1="/amzed3.png"
            imageUrl2="/amazed2.png"
            imageUrl3="/amazed.png"
            linkUrl="https://github.com/jeremyarmijo/Amazed"
            language="C"
            type="Elementary programming"
            group_size="Trio"
            duration_project="3 Weeks"
            begin_date="24 March"
        /> <br/> <br/>
        <Card
            title="42sh"
            description="The '42sh' project involves creating a feature-rich Unix shell from scratch. Students implement core shell functionalities such as command parsing, execution, job control, signal handling, and built-in commands. Advanced features include scripting capabilities, input/output redirection, pipelines, and environment variable management. This project enhances skills in systems programming, process control, and user interaction, providing in-depth experience in developing robust and efficient command-line interfaces"
            imageUrl1="/42sh1.png"
            imageUrl2="/42sh2.png"
            imageUrl3="/42sh3.png"
            linkUrl="https://github.com/jeremyarmijo/42sh"
            language="C"
            type="Elementary programming"
            group_size="Quatuor"
            duration_project="6 Weeks"
            begin_date="9 March"
        /> <br/> <br/>
        <Card
            title="My rpg"
            description="The 'my_rpg' project involves creating a role-playing game (RPG) from scratch. The program develop key features such as character creation, exploration, combat systems, inventory management, and quests. The project includes designing interactive environments and managing game states. This project enhances skills in game development, including graphics programming, event handling, and complex system integration, providing comprehensive experience in building a complete, interactive RPG."
            imageUrl1="/my_rpg1.png"
            imageUrl2="/my_rpg2.png"
            imageUrl3="/my_rpg3.png"
            linkUrl="https://github.com/jeremyarmijo/My_rpg"
            language="C"
            type="Graphical (Lib: CSFML)"
            group_size="Quatuor"
            duration_project="6 Weeks"
            begin_date="13 April"
        /> <br/> <br/>
        <Card
            title="My paint"
            description="The 'my_paint' project involves developing a simple drawing application similar to Microsoft Paint. The program implements basic functionality such as drawing, erasing, saving, loading, selecting colors and using tools such as pencil size manipulation and a help menu. The project focuses on handling user input, managing graphical rendering, and providing a user-friendly interface."
            imageUrl1="/my_paint1.png"
            imageUrl2="/my_paint2.png"
            imageUrl3="/my_paint3.png"
            linkUrl="https://github.com/jeremyarmijo/My_paint"
            language="C"
            type="Graphical (Lib: CSFML)"
            group_size="Duo"
            duration_project="3 Weeks"
            begin_date="24 February"
        /> <br/> <br/>
        <Card
            title="My navy"
            description="The 'my_navy' project involves creating a two-player naval battle game, similar to the classic Battleship game. The program implement game mechanics for placing ships, taking turns to fire at the opponent's grid, and determining hits and misses. The project includes managing player interactions, handling game state updates, and ensuring a smooth, turn-based gameplay experience."
            imageUrl1="/my_navy1.png"
            imageUrl2="/my_navy2.png"
            imageUrl3="/my_navy3.png"
            linkUrl="https://github.com/jeremyarmijo/My_navy"
            language="C"
            type="Elementary programming"
            group_size="Duo"
            duration_project="3 Weeks"
            begin_date="6 January"
        /> <br/> <br/>
        <Card
            title="Secured"
            description="The 'secured' project involves building a hash table and creating a custom hash function in C. The project aims to introduce students to hash tables and requires skills in handling arrays, linked lists, file and library handling, and dynamic programming algorithms."
            imageUrl1="/secured1.png"
            imageUrl2="/secured2.png"
            imageUrl3="/secured3.png"
            linkUrl="https://github.com/jeremyarmijo/Secured"
            language="C"
            type="Elementary programming"
            group_size="Duo"
            duration_project="3 Weeks"
            begin_date="30 Decembre"
        /> <br/> <br/>
        <Card
            title="My radar"
            description="The 'my_radar' project involves developing an air traffic simulation. This program create a visual representation of aircraft movements and radar detection zones. Key features include simulating aircraft trajectories, detecting potential collisions, and managing radar zones."
            imageUrl1="/my_radar1.png"
            imageUrl2="/my_radar2.png"
            imageUrl3="/my_radar3.png"
            linkUrl="https://github.com/jeremyarmijo/My_radar"
            language="C"
            type="Graphical (Lib: CSFML)"
            group_size="Solo"
            duration_project="5 Weeks"
            begin_date="2 December"
        /> <br/> <br/>
        <Card
            title="Organized"
            description="The 'organized' project involves creating a system to store and sort laboratory materials efficiently using linked lists. It includes commands to add, delete, display, and sort hardware items based on type, name, or ID. The project aims to bring order to a chaotic workspace by organizing materials into categories"
            imageUrl1="/organized1.png"
            imageUrl2="/organized2.png"
            imageUrl3="/organized3.png"
            linkUrl="https://github.com/jeremyarmijo/Organized"
            language="C"
            type="Elementary programming"
            group_size="Solo"
            duration_project="2 Weeks"
            begin_date="25 November"
        /> <br/> <br/>
        <Card
            title="My sokoban"
            description="The 'my_sokoban' project involves recreating the classic Sokoban game. Implementing game mechanics for moving a character to push boxes onto storage locations within a maze. The project focuses on map management, collision detection, user input handling, and tracking game state."
            imageUrl1="/my_sokoban1.png"
            imageUrl2="/my_sokoban2.png"
            imageUrl3="/my_sokoban3.png"
            linkUrl="https://github.com/jeremyarmijo/Sokoban"
            language="C"
            type="Elementary programming"
            group_size="Solo"
            duration_project="3 Weeks"
            begin_date="18 November"
        /> <br/> <br/>
        <Card
            title="My hunter"
            description="The 'my_hunter' project is a small video game based on the real Duck Hunt rules, where the player acts as a hunter shooting ducks that move across the screen. The game requires managing user inputs, displaying animated sprites, and adhering to specific requirements such as window management, sprite rendering, and input handling."
            imageUrl1="/my_hunter1.png"
            imageUrl2="/my_hunter2.png"
            imageUrl3="/my_hunter3.png"
            linkUrl="https://github.com/jeremyarmijo/My_hunter"
            language="C"
            type="Graphical (Lib: CSFML)"
            group_size="Solo"
            duration_project="3 Weeks"
            begin_date="11 November"
        /> <br/> <br/>
        <Card
            title="Setting up"
            description="The 'setting_up' project involves to find the largest square on a board '.' while avoiding obstacles 'o'. Boards can be read from files or generated based on parameters. Constraints for file boards include specific formatting rules. The program must print the board with the largest square marked. It also emphasizes using allowed functions."
            imageUrl1="/setting_up1.png"
            imageUrl2="/setting_up2.png"
            imageUrl3="/setting_up3.png"
            linkUrl="https://github.com/jeremyarmijo/Setting-up"
            language="C"
            type="Elementary programming"
            group_size="Solo"
            duration_project="3 Weeks"
            begin_date="4 November"
        /> <br/> <br/>
        <Card
            title="My ls"
            description="The 'my_ls' project involves creating a custom version of the Unix ls command. This project focuses on handling file system navigation, displaying directory contents, managing various flags (like -l, -a, and -d), and sorting files by different criteria. Students learn to manipulate file metadata, work with system calls, and manage complex data structures, enhancing their skills in C programming and Unix system programming."
            imageUrl1="/my_ls1.png"
            imageUrl2="/my_ls2.png"
            imageUrl3="/my_ls3.png"
            linkUrl="https://github.com/jeremyarmijo/My_ls"
            language="C"
            type="Elementary programming"
            group_size="Solo"
            duration_project="2 Weeks"
            begin_date="4 November"
        /> <br/> <br/>
        <Card
            title="My printf"
            description="The `my_printf` project involves creating a custom version of the C `printf` function. It teaches handling variadic functions, string formatting, and implementing format specifiers like `%d`, `%s`, and `%x`. This project enhances understanding of low-level programming and C language proficiency."
            imageUrl1="/my_printf1.png"
            imageUrl2="/my_printf2.png"
            imageUrl3="/my_printf3.png"
            linkUrl="https://github.com/jeremyarmijo/My_printf"
            language="C"
            type="Elementary programming"
            group_size="Solo"
            duration_project="2 Week"
            begin_date="21 October"
        /> <br/> <br/>
        </div>
    )
};

export default First_year;